/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Jol
 */
public class FrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public FrameInicial() {
        initComponents();
        URL iconURL = getClass().getResource("/trampo/hotelicon.png");
    ImageIcon icon = new ImageIcon(iconURL);
    this.setIconImage(icon.getImage());
        nameUser.setText("pombaloca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        nameUser = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        log_out = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cadhospede = new javax.swing.JMenuItem();
        pesquisahospede = new javax.swing.JMenuItem();
        jmenublalblabla = new javax.swing.JMenu();
        quart = new javax.swing.JMenuItem();
        cadQuarto = new javax.swing.JMenuItem();
        func = new javax.swing.JMenu();
        cadfunc = new javax.swing.JMenuItem();
        pesqfunc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadservico = new javax.swing.JMenuItem();
        servico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        pesqestoq = new javax.swing.JMenuItem();
        estoque = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.textHighlight);

        jLabel1.setText("Bem vindo ao BMS");

        nameUser.setText("Nome do usuário");

        logout.setText("Inicio");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");
        logout.add(jMenuItem1);

        log_out.setText("Logout");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        logout.add(log_out);

        jMenuBar1.add(logout);

        jMenu1.setText("Hóspedes");

        cadhospede.setText("Cadastro Hóspede");
        cadhospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadhospedeActionPerformed(evt);
            }
        });
        jMenu1.add(cadhospede);

        pesquisahospede.setText("Pesquisa Hóspede");
        pesquisahospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisahospedeActionPerformed(evt);
            }
        });
        jMenu1.add(pesquisahospede);

        jMenuBar1.add(jMenu1);

        jmenublalblabla.setText("Quartos");

        quart.setText("Quartos");
        quart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartActionPerformed(evt);
            }
        });
        jmenublalblabla.add(quart);

        cadQuarto.setText("Cadastro Quarto");
        cadQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadQuartoActionPerformed(evt);
            }
        });
        jmenublalblabla.add(cadQuarto);

        jMenuBar1.add(jmenublalblabla);

        func.setText("Funcionários");

        cadfunc.setText("Cadastro Funcionario");
        cadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadfuncActionPerformed(evt);
            }
        });
        func.add(cadfunc);

        pesqfunc.setText("PesquisaFuncionario");
        pesqfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqfuncActionPerformed(evt);
            }
        });
        func.add(pesqfunc);

        jMenuBar1.add(func);

        jMenu2.setText("Serviços");

        cadservico.setText("Cadastro de serviço");
        cadservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadservicoActionPerformed(evt);
            }
        });
        jMenu2.add(cadservico);

        servico.setText("Serviços");
        servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoActionPerformed(evt);
            }
        });
        jMenu2.add(servico);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Controle de Estoque");

        pesqestoq.setText("Pesquisa Estoque");
        pesqestoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqestoqActionPerformed(evt);
            }
        });
        jMenu5.add(pesqestoq);

        estoque.setText("Estoque");
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jMenu5.add(estoque);

        jMenuBar1.add(jMenu5);

        about.setText("Sobre");
        about.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                aboutMenuSelected(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(530, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
             this.dispose();
        FrameLogin log = new FrameLogin();
        log.setVisible(true);   
    }//GEN-LAST:event_log_outActionPerformed

    private void pesqestoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqestoqActionPerformed
        FormPesquisaEstoque pesqestoq = new FormPesquisaEstoque();
        pesqestoq.setVisible(true);
    }//GEN-LAST:event_pesqestoqActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        FrameLogin log = new FrameLogin();
        log.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed

    }//GEN-LAST:event_aboutActionPerformed

    private void aboutMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_aboutMenuSelected
JOptionPane.showMessageDialog(null, "Eu sou um software que precisa de um about");
    }//GEN-LAST:event_aboutMenuSelected

    private void cadhospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadhospedeActionPerformed
        FrameCadHospedes framecadhospedes = new FrameCadHospedes();
        framecadhospedes.setVisible(true);    
    }//GEN-LAST:event_cadhospedeActionPerformed

    private void pesquisahospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisahospedeActionPerformed
        FormPesquisaHospede formpesquisahosp = new FormPesquisaHospede();
        formpesquisahosp.setVisible(true);    
    }//GEN-LAST:event_pesquisahospedeActionPerformed

    private void pesqfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqfuncActionPerformed
        FormPesquisaFuncionario formpesquisafunc = new FormPesquisaFuncionario();
        formpesquisafunc.setVisible(true);    
    }//GEN-LAST:event_pesqfuncActionPerformed

    private void cadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadfuncActionPerformed
        FormFuncionario1 formcadfunc = new FormFuncionario1();
        formcadfunc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadfuncActionPerformed

    private void cadservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadservicoActionPerformed
        FormCadastroServico cadservice = new FormCadastroServico();
        cadservice.setVisible(true);    
    }//GEN-LAST:event_cadservicoActionPerformed

    private void servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoActionPerformed
        FormServico serv = new FormServico();
        serv.setVisible(true);
    }//GEN-LAST:event_servicoActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        FormEstoque estoq = new FormEstoque();
        estoq.setVisible(true);
    }//GEN-LAST:event_estoqueActionPerformed

    private void cadQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadQuartoActionPerformed
        FormCadastroQuarto cadquart = new FormCadastroQuarto();
        cadquart.setVisible(true);
    }//GEN-LAST:event_cadQuartoActionPerformed

    private void quartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartActionPerformed
        FormQuartos quarts = new FormQuartos();
        quarts.setVisible(true);
    }//GEN-LAST:event_quartActionPerformed

    private void testeMenuSelected(javax.swing.event.MenuEvent evt){
JOptionPane.showMessageDialog(null, "Eu sou um software que precisa de um about");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem cadQuarto;
    private javax.swing.JMenuItem cadfunc;
    private javax.swing.JMenuItem cadhospede;
    private javax.swing.JMenuItem cadservico;
    private javax.swing.JMenuItem estoque;
    private javax.swing.JMenu func;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu jmenublalblabla;
    private javax.swing.JMenuItem log_out;
    private javax.swing.JMenu logout;
    private javax.swing.JTextField nameUser;
    private javax.swing.JMenuItem pesqestoq;
    private javax.swing.JMenuItem pesqfunc;
    private javax.swing.JMenuItem pesquisahospede;
    private javax.swing.JMenuItem quart;
    private javax.swing.JMenuItem servico;
    // End of variables declaration//GEN-END:variables
}
